In [111]:
import pandas as pd
from datetime import datetime as dt

In [112]:
imd = pd.read_excel("data/IMD_Endoskopie.xlsx")
# imd.set_index("Lfd. Nr. Leistung", inplace = True)
material = pd.read_excel("data/Materialdokumentation.xlsx")
material.set_index("Auftragsnummer", inplace = True)

In [113]:
imd.drop(["Lfd.Nr", "Angelegt am", "Erfass.zeit", "Verabreichungsdatum", "Verabreichungszeit", "Geändert am", "Uhrzeit"], axis = 1, inplace = True)
imd.head()

,Laufende Nr. der Materialdokumentation,Status Materialdokumentation,Materialnummer,Materialtext,Name 1,Materialmenge,Mengeneinheit,Materialpreis,Währung,Anford. OE fachlich,Lfd. Nr. Leistung
0,1000003572,3,10129221.0,Biopsiezange Ø4 240cm Bx20 steril einweg,Boston Scientific,1,ST,6.78,EUR,3201,100999909
1,1000003573,3,11126032.0,Ballon f. Ballonapplikator MAJ-233 ster,OLYMPUS Deutschland GmbH,1,ST,23.30,EUR,3301,100939898
2,1000003574,3,11125327.0,Ballon f.Ballonapplikator MAJ-249 steril,OLYMPUS Deutschland GmbH,1,ST,23.09,EUR,4415,101192086
3,1000003574,3,10168546.0,Ultraschall-Kanüle HD-C G19,MICRO-TECH Europe GmbH,1,ST,117.81,EUR,4415,101192086
4,1000003575,3,11125327.0,Ballon f.Ballonapplikator MAJ-249 steril,OLYMPUS Deutschland GmbH,1,ST,23.09,EUR,3301,101275632

In [114]:
# Drop invalid material scans

select = imd["Status Materialdokumentation"] == 4
imd.drop(imd[select].index, axis = 0, inplace = True)
select = imd["Status Materialdokumentation"] == 2
imd.drop(imd[select].index, axis = 0, inplace = True)

In [115]:
material.drop(["U-beginn Datum", "U-Ende Datum", "Leistung_DGVS", "Untersucher"], axis = 1, inplace = True)
material.head()

                U-Dauer       Fachgebiet                Untersucher 2
Auftragsnummer
100006112          24.0  Endosonographie                          NaN
100002310          16.0     Gastroskopie                          NaN
97671673           25.0       Koloskopie                          NaN
98573033           10.0     Gastroskopie                          NaN
100011189          14.0     Gastroskopie  Dr. med. Reimer, Stanislaus

In [116]:
drop_values = ['MC_Gastroskopie', 'MC_Ileokoloskopie', 'MC_Koloskopie', 'MENELMGKE']
for value in drop_values:
    select = material["Fachgebiet"] == value
    material.drop(material[select].index, axis = 0, inplace = True)

In [117]:
material.shape

(1713, 3)

In [118]:
# get unique material id's
mat_ids = imd["Materialnummer"].unique()
len(mat_ids)

189

In [119]:
# Make empty mat cols
material.loc[:, mat_ids] = 0

In [120]:
benis_cnt = 0
for _id in material.index:
    if _id in imd_case_ids:
        _rows = imd[imd["Lfd. Nr. Leistung"] == _id]
        for index, row in _rows.iterrows():
            material.loc[_id, row["Materialnummer"]] = row["Materialmenge"]            
        
    else: 
        print(f"BEEEENIS {benis_cnt}")
        benis_cnt += 1

BEEEENIS 0
BEEEENIS 1
BEEEENIS 2
BEEEENIS 3
BEEEENIS 4
BEEEENIS 5
BEEEENIS 6
BEEEENIS 7
BEEEENIS 8
BEEEENIS 9
BEEEENIS 10
BEEEENIS 11
BEEEENIS 12
BEEEENIS 13
BEEEENIS 14
BEEEENIS 15
BEEEENIS 16
BEEEENIS 17
BEEEENIS 18
BEEEENIS 19
BEEEENIS 20
BEEEENIS 21
BEEEENIS 22
BEEEENIS 23
BEEEENIS 24
BEEEENIS 25
BEEEENIS 26
BEEEENIS 27
BEEEENIS 28
BEEEENIS 29
BEEEENIS 30
BEEEENIS 31
BEEEENIS 32
BEEEENIS 33
BEEEENIS 34
BEEEENIS 35
BEEEENIS 36
BEEEENIS 37
BEEEENIS 38
BEEEENIS 39
BEEEENIS 40
BEEEENIS 41
BEEEENIS 42
BEEEENIS 43
BEEEENIS 44
BEEEENIS 45
BEEEENIS 46
BEEEENIS 47
BEEEENIS 48
BEEEENIS 49
BEEEENIS 50
BEEEENIS 51
BEEEENIS 52
BEEEENIS 53
BEEEENIS 54
BEEEENIS 55
BEEEENIS 56
BEEEENIS 57
BEEEENIS 58
BEEEENIS 59
BEEEENIS 60
BEEEENIS 61
BEEEENIS 62
BEEEENIS 63
BEEEENIS 64
BEEEENIS 65
BEEEENIS 66
BEEEENIS 67
BEEEENIS 68
BEEEENIS 69
BEEEENIS 70
BEEEENIS 71
BEEEENIS 72
BEEEENIS 73
BEEEENIS 74
BEEEENIS 75
BEEEENIS 76
BEEEENIS 77
BEEEENIS 78
BEEEENIS 79
BEEEENIS 80
BEEEENIS 81
BEEEENIS 82
BEEEENIS 83
BEEEENIS 84
BEEEENIS 85
BEEEENIS 86
BEEEENIS 87
BEEEENIS 88
BEEEENIS 89
BEEEENIS 90
BEEEENIS 91
BEEEENIS 92
BEEEENIS 93
BEEEENIS 94
BEEEENIS 95
BEEEENIS 96
BEEEENIS 97
BEEEENIS 98
BEEEENIS 99
BEEEENIS 100
BEEEENIS 101
BEEEENIS 102
BEEEENIS 103
BEEEENIS 104
BEEEENIS 105
BEEEENIS 106
BEEEENIS 107
BEEEENIS 108
BEEEENIS 109
BEEEENIS 110
BEEEENIS 111
BEEEENIS 112
BEEEENIS 113
BEEEENIS 114
BEEEENIS 115
BEEEENIS 116
BEEEENIS 117
BEEEENIS 118
BEEEENIS 119
BEEEENIS 120
BEEEENIS 121
BEEEENIS 122
BEEEENIS 123
BEEEENIS 124
BEEEENIS 125
BEEEENIS 126
BEEEENIS 127
BEEEENIS 128
BEEEENIS 129
BEEEENIS 130
BEEEENIS 131
BEEEENIS 132
BEEEENIS 133
BEEEENIS 134
BEEEENIS 135
BEEEENIS 136
BEEEENIS 137
BEEEENIS 138
BEEEENIS 139
BEEEENIS 140
BEEEENIS 141
BEEEENIS 142
BEEEENIS 143
BEEEENIS 144
BEEEENIS 145
BEEEENIS 146
BEEEENIS 147
BEEEENIS 148
BEEEENIS 149
BEEEENIS 150
BEEEENIS 151
BEEEENIS 152
BEEEENIS 153
BEEEENIS 154
BEEEENIS 155
BEEEENIS 156
BEEEENIS 157
BEEEENIS 158
BEEEENIS 159
BEEEENIS 160
BEEEENIS 161
BEEEENIS 162
BEEEENIS 163
BEEEENIS 164
BEEEENIS 165
BEEEENIS 166
BEEEENIS 167
BEEEENIS 168
BEEEENIS 169
BEEEENIS 170
BEEEENIS 171
BEEEENIS 172
BEEEENIS 173
BEEEENIS 174
BEEEENIS 175
BEEEENIS 176
BEEEENIS 177
BEEEENIS 178
BEEEENIS 179
BEEEENIS 180
BEEEENIS 181
BEEEENIS 182
BEEEENIS 183
BEEEENIS 184
BEEEENIS 185
BEEEENIS 186
BEEEENIS 187
BEEEENIS 188
BEEEENIS 189
BEEEENIS 190
BEEEENIS 191
BEEEENIS 192
BEEEENIS 193
BEEEENIS 194
BEEEENIS 195
BEEEENIS 196
BEEEENIS 197
BEEEENIS 198
BEEEENIS 199
BEEEENIS 200
BEEEENIS 201
BEEEENIS 202
BEEEENIS 203
BEEEENIS 204
BEEEENIS 205
BEEEENIS 206
BEEEENIS 207
BEEEENIS 208
BEEEENIS 209
BEEEENIS 210
BEEEENIS 211
BEEEENIS 212
BEEEENIS 213
BEEEENIS 214
BEEEENIS 215
BEEEENIS 216
BEEEENIS 217
BEEEENIS 218
BEEEENIS 219
BEEEENIS 220
BEEEENIS 221
BEEEENIS 222
BEEEENIS 223
BEEEENIS 224
BEEEENIS 225
BEEEENIS 226
BEEEENIS 227
BEEEENIS 228
BEEEENIS 229
BEEEENIS 230
BEEEENIS 231
BEEEENIS 232
BEEEENIS 233
BEEEENIS 234
BEEEENIS 235
BEEEENIS 236
BEEEENIS 237
BEEEENIS 238
BEEEENIS 239
BEEEENIS 240
BEEEENIS 241
BEEEENIS 242
BEEEENIS 243
BEEEENIS 244
BEEEENIS 245
BEEEENIS 246
BEEEENIS 247
BEEEENIS 248
BEEEENIS 249
BEEEENIS 250
BEEEENIS 251
BEEEENIS 252
BEEEENIS 253
BEEEENIS 254
BEEEENIS 255
BEEEENIS 256
BEEEENIS 257
BEEEENIS 258
BEEEENIS 259
BEEEENIS 260
BEEEENIS 261
BEEEENIS 262
BEEEENIS 263
BEEEENIS 264
BEEEENIS 265
BEEEENIS 266
BEEEENIS 267
BEEEENIS 268
BEEEENIS 269
BEEEENIS 270
BEEEENIS 271
BEEEENIS 272
BEEEENIS 273
BEEEENIS 274
BEEEENIS 275
BEEEENIS 276
BEEEENIS 277
BEEEENIS 278
BEEEENIS 279
BEEEENIS 280
BEEEENIS 281
BEEEENIS 282
BEEEENIS 283
BEEEENIS 284
BEEEENIS 285
BEEEENIS 286
BEEEENIS 287
BEEEENIS 288
BEEEENIS 289
BEEEENIS 290
BEEEENIS 291
BEEEENIS 292
BEEEENIS 293
BEEEENIS 294
BEEEENIS 295
BEEEENIS 296
BEEEENIS 297
BEEEENIS 298
BEEEENIS 299
BEEEENIS 300
BEEEENIS 301
BEEEENIS 302
BEEEENIS 303
BEEEENIS 304
BEEEENIS 305
BEEEENIS 306
BEEEENIS 307
BEEEENIS 308
BEEEENIS 309
BEEEENIS 310
BEEEENIS 311
BEEEENIS 312
BEEEENIS 313
BEEEENIS 314
BEEEENIS 315
BEEEENIS 316
BEEEENIS 317
BEEEENIS 318
BEEEENIS 319
BEEEENIS 320
BEEEENIS 321
BEEEENIS 322
BEEEENIS 323
BEEEENIS 324
BEEEENIS 325
BEEEENIS 326
BEEEENIS 327
BEEEENIS 328
BEEEENIS 329
BEEEENIS 330
BEEEENIS 331
BEEEENIS 332
BEEEENIS 333
BEEEENIS 334
BEEEENIS 335
BEEEENIS 336
BEEEENIS 337
BEEEENIS 338
BEEEENIS 339
BEEEENIS 340
BEEEENIS 341
BEEEENIS 342
BEEEENIS 343
BEEEENIS 344
BEEEENIS 345
BEEEENIS 346
BEEEENIS 347
BEEEENIS 348
BEEEENIS 349
BEEEENIS 350
BEEEENIS 351
BEEEENIS 352
BEEEENIS 353
BEEEENIS 354
BEEEENIS 355
BEEEENIS 356
BEEEENIS 357
BEEEENIS 358
BEEEENIS 359
BEEEENIS 360

In [121]:
material.to_excel("data/features.xlsx")

In [102]:
material.head()

,U-Dauer,Fachgebiet,Untersucher,Untersucher 2,10129221.0,11126032.0,11125327.0,10168546.0,11129570.0,10132597.0,...,10172946.0,11100018.0,10191021.0,10148636.0,NaN,10119146.0,10178772.0,11122372.0,10164515.0,10157942.0
Auftragsnummer,,,,,,,,,,,,,,,,,,,,,
100006112,24.0,Endosonographie,"Dr. med. Kudlich, Theodor",NaN,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100002310,16.0,Gastroskopie,"Dr. med. Groneberg, Kaja",NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97671673,25.0,Koloskopie,PD Dr. Hann Alexander,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98573033,10.0,Gastroskopie,Dr. med. Daniel Fitting,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100011189,14.0,Gastroskopie,"Dr. med. Groneberg, Kaja","Dr. med. Reimer, Stanislaus",0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0